import { sendMail } from "@/lib/mailer"

export async function mailPaperReady(opts: {
  teacherEmail: string
  teacherName: string
  assignmentTitle: string
  subject: string
  assignmentId: string
  frontendUrl: string
}) {
  const url = `${opts.frontendUrl}/paper/${opts.assignmentId}`
  await sendMail({
    to: opts.teacherEmail,
    subject: `Your question paper is ready — ${opts.assignmentTitle}`,
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:32px 24px;background:#fff">
        <h2 style="margin:0 0 8px;font-size:20px;color:#111">Question paper ready ✓</h2>
        <p style="color:#555;margin:0 0 24px;font-size:15px">
          Hi ${opts.teacherName}, your paper for <strong>${opts.assignmentTitle}</strong>
          (${opts.subject}) has been generated by VedaAI.
        </p>
        <a href="${url}"
           style="display:inline-block;background:#e74c25;color:#fff;text-decoration:none;
                  padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px">
          View Question Paper
        </a>
        <p style="color:#aaa;font-size:12px;margin-top:32px">
          VedaAI — AI-powered exam paper generator
        </p>
      </div>`,
  })
}

export async function mailSubmissionConfirmed(opts: {
  studentEmail: string
  studentName: string
  assignmentTitle: string
  subject: string
  frontendUrl: string
}) {
  await sendMail({
    to: opts.studentEmail,
    subject: `Submission received — ${opts.assignmentTitle}`,
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:32px 24px;background:#fff">
        <h2 style="margin:0 0 8px;font-size:20px;color:#111">Submission received ✓</h2>
        <p style="color:#555;margin:0 0 24px;font-size:15px">
          Hi ${opts.studentName}, your answer sheet for
          <strong>${opts.assignmentTitle}</strong> (${opts.subject}) has been submitted.
          Your teacher will review it shortly.
        </p>
        <a href="${opts.frontendUrl}/student/home"
           style="display:inline-block;background:#4ebf7b;color:#fff;text-decoration:none;
                  padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px">
          Go to Dashboard
        </a>
        <p style="color:#aaa;font-size:12px;margin-top:32px">
          VedaAI — AI-powered exam paper generator
        </p>
      </div>`,
  })
}

export async function mailDeadlineReminder(opts: {
  studentEmail: string
  studentName: string
  assignmentTitle: string
  subject: string
  dueDate: Date
  assignmentId: string
  frontendUrl: string
}) {
  const due = opts.dueDate.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })
  const url = `${opts.frontendUrl}/student/paper/${opts.assignmentId}`
  await sendMail({
    to: opts.studentEmail,
    subject: `Reminder: ${opts.assignmentTitle} is due tomorrow`,
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:32px 24px;background:#fff">
        <h2 style="margin:0 0 8px;font-size:20px;color:#111">Assignment due tomorrow ⏰</h2>
        <p style="color:#555;margin:0 0 8px;font-size:15px">
          Hi ${opts.studentName}, this is a reminder that
          <strong>${opts.assignmentTitle}</strong> (${opts.subject}) is due on
          <strong>${due}</strong>.
        </p>
        <p style="color:#555;margin:0 0 24px;font-size:15px">
          If you haven't submitted yet, please do so before the deadline.
        </p>
        <a href="${url}"
           style="display:inline-block;background:#e74c25;color:#fff;text-decoration:none;
                  padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px">
          Submit Answer Sheet
        </a>
        <p style="color:#aaa;font-size:12px;margin-top:32px">
          VedaAI — AI-powered exam paper generator
        </p>
      </div>`,
  })
}
